def File_change(data_file):
    f = open(data_file)
    wf = open("C:/Users/ljm/Desktop/27.dat", "w")
    data = f.readline()
    data = data.replace("       ", " ")
    data = data.replace("     ", " ")
    data = data.replace("   ", " ")
    data = data.replace("  ", " ")
    data = data.replace("  ", " ")
    data = data.replace("  ", " ")
    data = data.replace(" ", '\t')
    wf.writelines(data)
    while data != "":
        data = f.readline()
        data = data.replace("       ", " ")
        data = data.replace("     ", " ")
        data = data.replace("   ", " ")
        data = data.replace("  ", " ")
        data = data.replace("  ", " ")
        data = data.replace("  ", " ")
        data = data.replace(" ", '\t')
        print(data)
        wf.writelines(data)
    wf.close()
    f.close()